# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:  Vincent | Lab
subtitle: 念念不忘，必有回响
name: Vincent | Lab
email: vincenttttwu@gmail.com
description: Vincent | Lab
keywords: Vincent,LLVM,Clang,lab,
encoding: "utf-8"
favicon: favicon.ico 
copyright: XinlongWu

repository: Xinlong-Wu/XinlongWu.github.io
url: https://xinlong-wu.github.io/XinlongWu.github.io/
enforce_ssl: xinlong-wu.github.io/XinlongWu.github.io/

# Sidebar to show popular repo
Github_info:
  github_url: https://github.com/Xinlong-Wu/
  side_bar_repo_limit: 3 # Number of repos to show
  side_bar_repo_black_list: ['zheda_curriculum','XinlongWu.github.io',]
  # side_bar_repo_show_list : 
  #   - name: test1
  #     description: for test
  #     stargazers_count: 0
  #     forks_count: 0
  #     updated_at: 2020/1/1
  #   - name: test2
  #     description: for test
  #     stargazers_count: 0
  #     forks_count: 0
  #     updated_at: 2020/1/1
  #   - name: test3
  #     description: for test
  #     stargazers_count: 0
  #     forks_count: 0
  #     updated_at: 2020/1/1


filing_site: http://beian.miit.gov.cn
filing_info: 京ICP备15067287号

## Gem
plugins:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true
  syntax_highlighter: rouge

syntax_highlighter_opts:
   coderay_line_numbers:  nil

# Pagination
paginate: 12
paginate_path: 'page:num'

# Navigation. top menu list
menus:

  -
    href: /about.html
    label: about

  -
    href: /archives.html
    label: archives
    target: _self   

  -
    href: /arch.html
    label: arch
    target: _self

  -
    href: /
    label: 中文
    target: _self

# Navigation. main menu list
navs:

  -
    href: /
    label: Home

  -
    href: /
    label: lable1
    target: _blank

  -
    href: /
    label: lable2
    target: _self
    subnav:

      -
        subHref: /
        subLabel: sub Label1

      -
        subHref: /
        subLabel: sub Label2

  -
    href: /
    label: label3
    target: _blank
    subnav:

      -
        subHref: /
        subLabel: sub Label1
        
      -
        subHref: /
        subLabel: sub Label2
        target: _blank

  -
    href: /archives.html
    label: Archives
    target: _self



# labels. my blog key words
labels:

  -
    href: /
    label: Vincnet     
    target: _self

  -
    label: Templet1
    target: _blank

  -
    href: /
    label: 支持中文
    target: _blank


# selected articles
classes:

  -
    href: /about.html
    name: about

  -
    href: /archives.html
    name: archives
    describe: describe

  -
    href: /arch.html
    name: arch
    describe: 支持中文

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# Google Analytics
# analytics :
# provider : google
#   google :
#     tracking_id : ''  # ex. UA-72165600-X


# For about.html. Fell free to create your own!
skill_keywords: [Clang/LLVM,Compiler,LLD,C++,Java]


# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: wuxinlong
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: ityouknow
    repo: blog-comments
    oauth:
        client_id: 61bfc53d957e74e78f8f
        client_secret: 31c61e66cdcc9ada8db2267ee779d0bdafac434c
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: Xinlong-Wu
    repo: blog-comment
    clientID: c596b143ef1b081c1bda
    clientSecret: 7519cc6acf1c843c8ac8e0bbcf9d05a72a9e111d
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false
