name: Jekyll Templete CI

on:
  push:
    branches: [ templete ]
  pull_request:
    branches: [ templete ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: templete
      - name: Cache Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version : 3.0.3
        run: |
              bundle exec jekyll build
#       - name: Jekyll build check
#         uses: helaili/jekyll-action@2.2.0
#         with:
#           build_only: true
#           token: ${{ secrets.GITHUB_TOKEN }}
      
  Push_to_Blog:
    needs: [ build ]
    uses: ./.github/workflows/TempleteUpdater.yml
    name: Push to Blog
