name: Jekyll Templete CI

on:
  push:
    branches: [ templete ]
  pull_request:
    branches: [ templete ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build Jekyll
      uses: helaili/jekyll-action@2.2.0
      with: 
        build_only: true
        gem_src: ./
        token: ${{ secrets.GITHUB_TOKEN }}
      
      
  Push_to_Blog:
    needs: [ build ]
    uses: ./.github/workflows/TempleteUpdater.yml
    name: Push to Blog
