name: Jekyll Templete CI

on:
  push:
    branches: [ templete ]
  pull_request:
    branches: [ templete ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: templete
    - name: Build Jekyll
      uses: helaili/jekyll-action@2.2.0
      with: 
        build_only: true
        token: ${{ secrets.GITHUB_TOKEN }}
        pre_build_commands: "bundle update --bundler"
      
      
  Push_to_Blog:
    needs: [ build ]
    uses: ./.github/workflows/TempleteUpdater.yml
    name: Push to Blog
