name: Jekyll Templete CI

on:
  push:
    branches: [ templete ]
  pull_request:
    branches: [ templete ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
#     - uses: jerryjvl/jekyll-build-action@v1
#       name: Build Jekyll
      - name: jekyll-deploy
        uses: DavidS/jekyll-deploy@1.1.1
        with:
          build-only: true
      
  Push_to_Blog:
    needs: [ build ]
    uses: ./.github/workflows/TempleteUpdater.yml
    name: Push to Blog
