name: Jekyll Templete CI

on:
  push:
    branches: [ templete ]
  pull_request:
    branches: [ templete ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: templete
      - name: jekyll-build-check
        uses: lemonarc/jekyll-action@1.0.0
      
  Push_to_Blog:
    needs: [ build ]
    uses: ./.github/workflows/TempleteUpdater.yml
    name: Push to Blog
