name: Jekyll Templete CI

on:
  push:
    branches: [ templete ]
  pull_request:
    branches: [ templete ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: jerryjvl/jekyll-build-action@v1
      name: Build Jekyll
      
  Push_to_Blog:
    uses: ./.github/workflows/TempleteUpdater.yml
    name: Push to Blog
