name: Jekyll CI Pre-merge check

on:
  push:
    branches: [ templete ]
  pull_request:
    branches: [ templete, main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: jerryjvl/jekyll-build-action@v1
      name: Build Jekyll
      
    - name: Done
      run: |
