name: Jekyll Templete CI

on:
  push:
    branches: [ templete ]
  pull_request:
    branches: [ templete ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: helaili/jekyll-action@2.2.0
      name: Jekyll Actions
      
    - name: Sync output to S3
      run: |
